
[functions.notificar-novo-usuario]
enabled = true
verify_jwt = true
import_map = "./functions/notificar-novo-usuario/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notificar-novo-usuario/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notificar-novo-usuario/*.html" ]

[functions.notificar-novo-negocio]
enabled = true
verify_jwt = true
import_map = "./functions/notificar-novo-negocio/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/notificar-novo-negocio/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/notificar-novo-negocio/*.html" ]
